/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BooksIndexRouteImport } from './routes/books/index'
import { Route as ChaptersChapterIdRouteImport } from './routes/chapters/$chapterId'
import { Route as BooksBookIdRouteRouteImport } from './routes/books/$bookId/route'
import { Route as BooksBookIdIndexRouteImport } from './routes/books/$bookId/index'
import { Route as BooksBookIdPlotRouteImport } from './routes/books/$bookId/plot'
import { Route as BooksBookIdLocationsRouteImport } from './routes/books/$bookId/locations'
import { Route as BooksBookIdCharactersRouteImport } from './routes/books/$bookId/characters'
import { Route as BooksBookIdChaptersRouteImport } from './routes/books/$bookId/chapters'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersChapterIdRoute = ChaptersChapterIdRouteImport.update({
  id: '/chapters/$chapterId',
  path: '/chapters/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdRouteRoute = BooksBookIdRouteRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdIndexRoute = BooksBookIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BooksBookIdRouteRoute,
} as any)
const BooksBookIdPlotRoute = BooksBookIdPlotRouteImport.update({
  id: '/plot',
  path: '/plot',
  getParentRoute: () => BooksBookIdRouteRoute,
} as any)
const BooksBookIdLocationsRoute = BooksBookIdLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => BooksBookIdRouteRoute,
} as any)
const BooksBookIdCharactersRoute = BooksBookIdCharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => BooksBookIdRouteRoute,
} as any)
const BooksBookIdChaptersRoute = BooksBookIdChaptersRouteImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => BooksBookIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/books/$bookId': typeof BooksBookIdRouteRouteWithChildren
  '/chapters/$chapterId': typeof ChaptersChapterIdRoute
  '/books/': typeof BooksIndexRoute
  '/books/$bookId/chapters': typeof BooksBookIdChaptersRoute
  '/books/$bookId/characters': typeof BooksBookIdCharactersRoute
  '/books/$bookId/locations': typeof BooksBookIdLocationsRoute
  '/books/$bookId/plot': typeof BooksBookIdPlotRoute
  '/books/$bookId/': typeof BooksBookIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/chapters/$chapterId': typeof ChaptersChapterIdRoute
  '/books': typeof BooksIndexRoute
  '/books/$bookId/chapters': typeof BooksBookIdChaptersRoute
  '/books/$bookId/characters': typeof BooksBookIdCharactersRoute
  '/books/$bookId/locations': typeof BooksBookIdLocationsRoute
  '/books/$bookId/plot': typeof BooksBookIdPlotRoute
  '/books/$bookId': typeof BooksBookIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/books/$bookId': typeof BooksBookIdRouteRouteWithChildren
  '/chapters/$chapterId': typeof ChaptersChapterIdRoute
  '/books/': typeof BooksIndexRoute
  '/books/$bookId/chapters': typeof BooksBookIdChaptersRoute
  '/books/$bookId/characters': typeof BooksBookIdCharactersRoute
  '/books/$bookId/locations': typeof BooksBookIdLocationsRoute
  '/books/$bookId/plot': typeof BooksBookIdPlotRoute
  '/books/$bookId/': typeof BooksBookIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/books/$bookId'
    | '/chapters/$chapterId'
    | '/books/'
    | '/books/$bookId/chapters'
    | '/books/$bookId/characters'
    | '/books/$bookId/locations'
    | '/books/$bookId/plot'
    | '/books/$bookId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/chapters/$chapterId'
    | '/books'
    | '/books/$bookId/chapters'
    | '/books/$bookId/characters'
    | '/books/$bookId/locations'
    | '/books/$bookId/plot'
    | '/books/$bookId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/books/$bookId'
    | '/chapters/$chapterId'
    | '/books/'
    | '/books/$bookId/chapters'
    | '/books/$bookId/characters'
    | '/books/$bookId/locations'
    | '/books/$bookId/plot'
    | '/books/$bookId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  BooksBookIdRouteRoute: typeof BooksBookIdRouteRouteWithChildren
  ChaptersChapterIdRoute: typeof ChaptersChapterIdRoute
  BooksIndexRoute: typeof BooksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/$chapterId': {
      id: '/chapters/$chapterId'
      path: '/chapters/$chapterId'
      fullPath: '/chapters/$chapterId'
      preLoaderRoute: typeof ChaptersChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId/': {
      id: '/books/$bookId/'
      path: '/'
      fullPath: '/books/$bookId/'
      preLoaderRoute: typeof BooksBookIdIndexRouteImport
      parentRoute: typeof BooksBookIdRouteRoute
    }
    '/books/$bookId/plot': {
      id: '/books/$bookId/plot'
      path: '/plot'
      fullPath: '/books/$bookId/plot'
      preLoaderRoute: typeof BooksBookIdPlotRouteImport
      parentRoute: typeof BooksBookIdRouteRoute
    }
    '/books/$bookId/locations': {
      id: '/books/$bookId/locations'
      path: '/locations'
      fullPath: '/books/$bookId/locations'
      preLoaderRoute: typeof BooksBookIdLocationsRouteImport
      parentRoute: typeof BooksBookIdRouteRoute
    }
    '/books/$bookId/characters': {
      id: '/books/$bookId/characters'
      path: '/characters'
      fullPath: '/books/$bookId/characters'
      preLoaderRoute: typeof BooksBookIdCharactersRouteImport
      parentRoute: typeof BooksBookIdRouteRoute
    }
    '/books/$bookId/chapters': {
      id: '/books/$bookId/chapters'
      path: '/chapters'
      fullPath: '/books/$bookId/chapters'
      preLoaderRoute: typeof BooksBookIdChaptersRouteImport
      parentRoute: typeof BooksBookIdRouteRoute
    }
  }
}

interface BooksBookIdRouteRouteChildren {
  BooksBookIdChaptersRoute: typeof BooksBookIdChaptersRoute
  BooksBookIdCharactersRoute: typeof BooksBookIdCharactersRoute
  BooksBookIdLocationsRoute: typeof BooksBookIdLocationsRoute
  BooksBookIdPlotRoute: typeof BooksBookIdPlotRoute
  BooksBookIdIndexRoute: typeof BooksBookIdIndexRoute
}

const BooksBookIdRouteRouteChildren: BooksBookIdRouteRouteChildren = {
  BooksBookIdChaptersRoute: BooksBookIdChaptersRoute,
  BooksBookIdCharactersRoute: BooksBookIdCharactersRoute,
  BooksBookIdLocationsRoute: BooksBookIdLocationsRoute,
  BooksBookIdPlotRoute: BooksBookIdPlotRoute,
  BooksBookIdIndexRoute: BooksBookIdIndexRoute,
}

const BooksBookIdRouteRouteWithChildren =
  BooksBookIdRouteRoute._addFileChildren(BooksBookIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  BooksBookIdRouteRoute: BooksBookIdRouteRouteWithChildren,
  ChaptersChapterIdRoute: ChaptersChapterIdRoute,
  BooksIndexRoute: BooksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
